---
platform: linux
image_resource:
    type: docker-image
    source:
        repository: maven
inputs:
    - name: source-code

caches:
    - path: /root/.m2/repository

run:
    path: mvn
    args:
        - compile
        - -f
        - source-code/pom.xml