steps:
- task: Docker@2
  inputs:
    containerRegistry: 'mydockerhub'
    repository: 'tomcatwar'
    command: 'buildAndPush'
    Dockerfile: '$(Build.SourcesDirectory)/Jenkins-Capstone-Project/docker/Dockerfile'
    buildContext: '$(Build.SourcesDirectory)/war-ado'