parameters:
- name: CONTAINERREGISTRY
  default: ''
- name: REPOSITORY
  type: string
- name: DOCKERFILEPATH
  type: string
- name: BUILDCONTEXT
  type: string
- name: TAGS
  type: string

steps:
- task: Docker@2
  inputs:
    containerRegistry: ${{ parameters.CONTAINERREGISTRY }}
    repository: ${{ parameters.REPOSITORY }}
    command: 'buildAndPush'
    Dockerfile: ${{ parameters.DOCKERFILEPATH }}
    # Dockerfile: '$(Build.SourcesDirectory)/Jenkins-Capstone-Project/docker/Dockerfile'
    buildContext: ${{ paramters.BUILDCONTEXT }}
    # buildContext: '$(Build.SourcesDirectory)/war-ado'
    tags: ${{ parameters.TAGS }}