---
resources:
    - name: source-code
      type: git
      icon: github
      source:
        uri: https://github.com/DipayanP007/Jenkins-Capstone-Project.git
        branch: Development

jobs:
    - name: clean
      build_log_retention:
        builds: 5
        minimum_succeeded_builds: 1
      plan:
        - get: source-code
          trigger: true
        - task: maven-clean
          file: source-code/ci/tasks/clean-task.yml
    - name: compile
      build_log_retention:
        builds: 5
        minimum_succeeded_builds: 1
      plan:
        - get: source-code
          passed: [clean]
          trigger: true
        - task: maven-compile
          file: source-code/ci/tasks/compile-task.yml
    - name: package
      build_log_retention:
        builds: 5
        minimum_succeeded_builds: 1
      plan:
        - get: source-code
          passed: [compile]
          trigger: true
        - task: maven-package
          file: source-code/ci/tasks/package-task.yml